// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: skylinechart.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct SkylineChart: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var numZones: Int32 = 0

  var width: [Int32] = []

  var intensity: [Int32] = []

  var zone: [Int32] = []

  var minIntensity: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension SkylineChart: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SkylineChart"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}num_zones\0\u{1}width\0\u{1}intensity\0\u{1}zone\0\u{3}min_intensity\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.numZones) }()
      case 2: try { try decoder.decodeRepeatedInt32Field(value: &self.width) }()
      case 3: try { try decoder.decodeRepeatedInt32Field(value: &self.intensity) }()
      case 4: try { try decoder.decodeRepeatedInt32Field(value: &self.zone) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.minIntensity) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.numZones != 0 {
      try visitor.visitSingularInt32Field(value: self.numZones, fieldNumber: 1)
    }
    if !self.width.isEmpty {
      try visitor.visitPackedInt32Field(value: self.width, fieldNumber: 2)
    }
    if !self.intensity.isEmpty {
      try visitor.visitPackedInt32Field(value: self.intensity, fieldNumber: 3)
    }
    if !self.zone.isEmpty {
      try visitor.visitPackedInt32Field(value: self.zone, fieldNumber: 4)
    }
    if self.minIntensity != 0 {
      try visitor.visitSingularInt32Field(value: self.minIntensity, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SkylineChart, rhs: SkylineChart) -> Bool {
    if lhs.numZones != rhs.numZones {return false}
    if lhs.width != rhs.width {return false}
    if lhs.intensity != rhs.intensity {return false}
    if lhs.zone != rhs.zone {return false}
    if lhs.minIntensity != rhs.minIntensity {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
